export const BOSS_LIST = [
  "발록",
  "자쿰",
  "혼테일",
  "힐라",
  "피에르",
  "반반",
  "블러디퀸",
  "벨룸",
  "반 레온",
  "아카이럼",
  "매그너스",
  "핑크빈",
  "시그너스",
  "스우",
  "우르스",
  "데미안",
  "밸러드",
  "란마루",
  "노히메",
  "루시드",
  "크루스",
  "카웅",
  "파풀라투스",
  "윌",
  "진 힐라",
  "검은 마법사",
  "더스크",
  "듄켈",
  "선택받은 세렌",
  "가디언 엔젤 슬라임",
  "감시자 칼로스",
];
export const ORDER_BOSS = [14, 0, 1, 10, 3, 21, 22, 4, 5, 6, 7, 8, 2, 9, 11, 12, 13, 15, 29, 19, 23, 26, 24, 27, 25, 28, 30];

export const DIFFICULTY = ["EASY", "NORMAL", "HARD", "CHAOS", "EXTREME"];
export const BOSS_DIFFICULTY_COLOR = [
  { background: "linear-gradient(#999, #777)", color: "#fff", border: "1px solid #aaa" },
  { background: "linear-gradient(#4bb, #289)", color: "#fff", border: "1px solid #5cd" },
  { background: "linear-gradient(#d69, #b36)", color: "#fff", border: "1px solid #d58" },
  { background: "linear-gradient(#444, #222)", color: "#db8", border: "1px solid #db8" },
  { background: "linear-gradient(#444, #222)", color: "#fff", border: "1px solid #e36" },
];

export const BOSS_DIFFICULTY: { name: string; difficulty: (0 | 1 | 2 | 3 | 4)[] }[] = [
  { name: "발록", difficulty: [1] },
  { name: "자쿰", difficulty: [0, 1, 3] },
  { name: "혼테일", difficulty: [0, 1, 3] },
  { name: "힐라", difficulty: [1, 2] },
  { name: "피에르", difficulty: [1, 3] },
  { name: "반반", difficulty: [1, 3] },
  { name: "블러디퀸", difficulty: [1, 3] },
  { name: "벨룸", difficulty: [1, 3] },
  { name: "반 레온", difficulty: [0, 1, 2] },
  { name: "아카이럼", difficulty: [0, 1] },
  { name: "매그너스", difficulty: [0, 1, 2] },
  { name: "핑크빈", difficulty: [1, 3] },
  { name: "시그너스", difficulty: [0, 1] },
  { name: "스우", difficulty: [1, 2] },
  { name: "우르스", difficulty: [1] },
  { name: "데미안", difficulty: [1, 2] },
  { name: "밸러드", difficulty: [] },
  { name: "란마루", difficulty: [] },
  { name: "노히메", difficulty: [] },
  { name: "루시드", difficulty: [0, 1, 2] },
  { name: "크루스", difficulty: [] },
  { name: "카웅", difficulty: [1] },
  { name: "파풀라투스", difficulty: [0, 1, 3] },
  { name: "윌", difficulty: [0, 1, 2] },
  { name: "진 힐라", difficulty: [1, 2] },
  { name: "검은 마법사", difficulty: [2, 4] },
  { name: "더스크", difficulty: [1, 3] },
  { name: "듄켈", difficulty: [1, 2] },
  { name: "선택받은 세렌", difficulty: [1, 2] },
  { name: "가디언 엔젤 슬라임", difficulty: [1, 3] },
  { name: "감시자 칼로스", difficulty: [3] },
];

export const CRYSTAL_PRICE = [
  { type: "day", difficulty: 0, name: "자쿰", price: 119835 },
  { type: "day", difficulty: 1, name: "자쿰", price: 366997 },
  { type: "day", difficulty: 0, name: "파풀라투스", price: 410135 },
  { type: "day", difficulty: 0, name: "매그너스", price: 432605 },
  { type: "day", difficulty: 1, name: "힐라", price: 479343 },
  { type: "day", difficulty: 0, name: "혼테일", price: 528474 },
  { type: "day", difficulty: 1, name: "블러디퀸", price: 580003 },
  { type: "day", difficulty: 1, name: "반반", price: 580003 },
  { type: "day", difficulty: 1, name: "피에르", price: 580003 },
  { type: "day", difficulty: 1, name: "벨룸", price: 580003 },
  { type: "day", difficulty: 1, name: "혼테일", price: 606666 },
  { type: "day", difficulty: 0, name: "반 레온", price: 633927 },
  { type: "day", difficulty: 0, name: "아카이럼", price: 690249 },
  { type: "day", difficulty: 1, name: "카웅", price: 748970 },
  { type: "day", difficulty: 3, name: "혼테일", price: 810086 },
  { type: "day", difficulty: 1, name: "핑크빈", price: 841544 },
  { type: "day", difficulty: 1, name: "반 레온", price: 873601 },
  { type: "day", difficulty: 2, name: "반 레온", price: 1467984 },
  { type: "day", difficulty: 1, name: "아카이럼", price: 1510227 },
  { type: "day", difficulty: 1, name: "매그너스", price: 1553066 },
  { type: "day", difficulty: 1, name: "파풀라투스", price: 1596506 },
  { type: "week", difficulty: 0, name: "시그너스", price: 5496394 },
  { type: "week", difficulty: 2, name: "힐라", price: 6936489 },
  { type: "week", difficulty: 3, name: "핑크빈", price: 7923110 },
  { type: "week", difficulty: 1, name: "시그너스", price: 9039130 },
  { type: "week", difficulty: 3, name: "자쿰", price: 9741285 },
  { type: "week", difficulty: 3, name: "블러디퀸", price: 9806780 },
  { type: "week", difficulty: 3, name: "반반", price: 9818154 },
  { type: "week", difficulty: 3, name: "피에르", price: 9838932 },
  { type: "week", difficulty: 2, name: "매그너스", price: 11579023 },
  { type: "week", difficulty: 3, name: "벨룸", price: 12590202 },
  { type: "week", difficulty: 3, name: "파풀라투스", price: 26725937 },
  { type: "week", difficulty: 1, name: "스우", price: 33942566 },
  { type: "week", difficulty: 1, name: "데미안", price: 35517853 },
  { type: "week", difficulty: 1, name: "가디언 엔젤 슬라임", price: 46935874 },
  { type: "week", difficulty: 0, name: "루시드", price: 48058319 },
  { type: "week", difficulty: 0, name: "윌", price: 52139127 },
  { type: "week", difficulty: 1, name: "루시드", price: 57505626 },
  { type: "week", difficulty: 1, name: "윌", price: 66311463 },
  { type: "week", difficulty: 1, name: "더스크", price: 71054562 },
  { type: "week", difficulty: 1, name: "듄켈", price: 76601412 },
  { type: "week", difficulty: 2, name: "데미안", price: 112480613 },
  { type: "week", difficulty: 2, name: "스우", price: 118294192 },
  { type: "week", difficulty: 2, name: "루시드", price: 131095655 },
  { type: "week", difficulty: 2, name: "윌", price: 145038483 },
  { type: "week", difficulty: 1, name: "진 힐라", price: 148112376 },
  { type: "week", difficulty: 3, name: "가디언 엔젤 슬라임", price: 155492141 },
  { type: "week", difficulty: 3, name: "더스크", price: 160173752 },
  { type: "week", difficulty: 2, name: "듄켈", price: 168609280 },
  { type: "week", difficulty: 2, name: "진 힐라", price: 190159452 },
  { type: "week", difficulty: 1, name: "선택받은 세렌", price: 196904752 },
  { type: "week", difficulty: 2, name: "선택받은 세렌", price: 267825621 },
  { type: "week", difficulty: 3, name: "감시자 칼로스", price: 300000000 },
  { type: "week", difficulty: 4, name: "선택받은 세렌", price: 1071302484 },
  { type: "month", difficulty: 2, name: "검은 마법사", price: 1418809857 },
  { type: "month", difficulty: 4, name: "검은 마법사", price: 5675239428 },
];

export const BOSS_IMAGES = {
  PATHNAME: "/images/boss/",
  BACKGROUND: "Main.Move_wnd.backgrnd.png",
  BTN: ".btBoss.normal.0.png",
  BTN_MOUSEOVER: ".btBoss.mouseOver.0.png",
  BTN_CHECKED: ".btBoss.checked.0.png",
  ICON: ".Icon.normal.0.png",
  MOB: ".mob.png",
};
